= Prerequisites For Labs

== Install CF CLI and GIT CLI
- [Cloud Foundry CLI](https://console.run.pivotal.io/tools)
- [Git Client](https://git-scm.com/downloads)

**Verify the installation**
``` 
$ cf --version
$ git --version 
```

== Install Concourse && FLY CLI

. In a browser navigate to https://concoursetutorial.com/ and follow the instructions in "Getting Started" section.

== Target and Login to Concourse Env

. Execute the fly target command to connect to the Concourse environment.  When prompted to a username and password enter the credentials provided to you by your instructor.
+
[source,bash]
---------------------------------------------------------------------
$ fly --target tutorial login --concourse-url http://127.0.0.1:8080 -u admin -p admin
---------------------------------------------------------------------

. Execute the fly login command, entering the credentials again when prompted.
+
[source,bash]
---------------------------------------------------------------------
$ fly -t tutorial login                                                                                                                              1 ↵
username: admin
password:

target saved
---------------------------------------------------------------------

== Create a GIT repository to hold your concourse pipeline and artifacts

. Fork this git repository:  https://github.com/shiva-pivotal/concourse-workshop

. Clone this repository to your local desktop
+
[source,bash]
---------------------------------------------------------------------
$ git clone <YOUR-GIT-URL>
---------------------------------------------------------------------

. In your terminal window change directories to the root of your cloned git repo.  We'll use this location as a base for most our commands in the workshop
